add image pull command

diff --git a/moodled b/moodled
--- a/moodled
+++ b/moodled
@@ -16,48 +16,57 @@ MOODLE_BRANCH=MOODLE_402_STABLE
 MOODLE_COMPOSE_CMD=$MOODLE_DOCKER_DIR/bin/moodle-docker-compose
 MOODLE_DB_WAIT_CMD=$MOODLE_DOCKER_DIR/bin/moodle-docker-wait-for-db
 
+# pull images
+# early exit if we are shutting down
+if [ "$1" == "pull" ]; then
+  docker compose -f ocis/ocis.yml pull
+  "$MOODLE_COMPOSE_CMD" pull
+
+  exit 0
+fi
+
 # check docker compose version
 # REQUIRED: >=2.19
 docker_compose_version=$(docker compose version --short)
 major=$(echo "$docker_compose_version" | cut -d. -f1)
 minor=$(echo "$docker_compose_version" | cut -d. -f2)
 if [ "$major" != "2" ] || [ "$minor" -lt "19" ]; then
-    echo "[ERR] docker compose >=2.19 is REQUIRED, but found $docker_compose_version"
-    exit 1
+  echo "[ERR] docker compose >=2.19 is REQUIRED, but found $docker_compose_version"
+  exit 1
 fi
 
 # check extra hosts
 match=$(grep "$EXTRA_HOST" /etc/hosts)
 if [ "$match" == "" ] || echo "$match" | grep -q '#'; then
-    echo "Adding '$EXTRA_HOST' to /etc/hosts"
-    echo -e "127.0.0.1	$EXTRA_HOST" | sudo tee -a /etc/hosts >/dev/null
+  echo "Adding '$EXTRA_HOST' to /etc/hosts"
+  echo -e "127.0.0.1	$EXTRA_HOST" | sudo tee -a /etc/hosts >/dev/null
 fi
 
 # check ocis certs
 OCIS_CERTS_DIR=$PWD/ocis/certs
 if [ ! -f "$OCIS_CERTS_DIR"/ocis.crt ] || [ ! -f "$OCIS_CERTS_DIR"/ocis.pem ]; then
-    rm -rf "$OCIS_CERTS_DIR"
-    mkdir -p "$OCIS_CERTS_DIR"
-    openssl req -x509 -newkey rsa:2048 -keyout "$OCIS_CERTS_DIR"/ocis.pem -out "$OCIS_CERTS_DIR"/ocis.crt -nodes -days 365 -subj "/CN=$EXTRA_HOST"
+  rm -rf "$OCIS_CERTS_DIR"
+  mkdir -p "$OCIS_CERTS_DIR"
+  openssl req -x509 -newkey rsa:2048 -keyout "$OCIS_CERTS_DIR"/ocis.pem -out "$OCIS_CERTS_DIR"/ocis.crt -nodes -days 365 -subj "/CN=$EXTRA_HOST"
 fi
 
 # moodle setup
 if [ ! -d "$MOODLE_DOCKER_WWWROOT" ]; then
-    git clone https://github.com/moodle/moodle.git --branch "$MOODLE_BRANCH" --single-branch --depth=1
-    cd moodle/repository/ || exit
-    git clone https://github.com/owncloud/moodle-repository_ocis.git ocis
-    cd ../../ || exit
+  git clone https://github.com/moodle/moodle.git --branch "$MOODLE_BRANCH" --single-branch --depth=1
+  cd moodle/repository/ || exit
+  git clone https://github.com/owncloud/moodle-repository_ocis.git ocis
+  cd ../../ || exit
 fi
 if [ ! -d "$MOODLE_DOCKER_DIR" ]; then
-    git clone https://github.com/moodlehq/moodle-docker.git
+  git clone https://github.com/moodlehq/moodle-docker.git
 fi
 if [ ! -f "$MOODLE_DOCKER_WWWROOT/config.php" ]; then
-    cp "$MOODLE_DOCKER_DIR"/config.docker-template.php "$MOODLE_DOCKER_WWWROOT"/config.php
-    sed -i 's/"http:\/\/{$host}";/"https:\/\/{$host}";\n\t$CFG->sslproxy = true;/g' "$MOODLE_DOCKER_WWWROOT"/config.php
+  cp "$MOODLE_DOCKER_DIR"/config.docker-template.php "$MOODLE_DOCKER_WWWROOT"/config.php
+  sed -i 's/"http:\/\/{$host}";/"https:\/\/{$host}";\n\t$CFG->sslproxy = true;/g' "$MOODLE_DOCKER_WWWROOT"/config.php
 fi
 
 if [ ! -f "$MOODLE_DOCKER_DIR/local.yml" ]; then
-    cat >"$MOODLE_DOCKER_DIR/local.yml" <<EOF
+  cat >"$MOODLE_DOCKER_DIR/local.yml" <<EOF
 services:
   webserver:
     labels:
@@ -112,7 +121,7 @@ docker compose -f ocis/ocis.yml down -v
 
 # early exit if we are shutting down
 if [ "$1" == "down" ]; then
-    exit 0
+  exit 0
 fi
 
 # start moodle services
@@ -126,25 +135,25 @@ docker compose -f ocis/ocis.yml up -d
 timeout=30
 start_time=$(date +%s)
 while [ "$(curl -sk https://$EXTRA_HOST:9200/ocs/v1.php/cloud/capabilities -w %\{http_code\} -o /dev/null)" != "200" ]; do
-    curr_time=$(date +%s)
-    elapsed_time=$(($curr_time - $start_time))
-    if [ $elapsed_time -gt $timeout ]; then
-        echo "[ERR] ocis was not ready after $timeout seconds"
-        exit 1
-    fi
-    sleep 1
+  curr_time=$(date +%s)
+  elapsed_time=$(($curr_time - $start_time))
+  if [ $elapsed_time -gt $timeout ]; then
+    echo "[ERR] ocis was not ready after $timeout seconds"
+    exit 1
+  fi
+  sleep 1
 done
 
 # install moodle
 "$MOODLE_DB_WAIT_CMD"
 "$MOODLE_COMPOSE_CMD" exec webserver \
-    php admin/cli/install_database.php \
-    --agree-license \
-    --fullname="Docker moodle" \
-    --shortname="docker_moodle" \
-    --summary="Docker moodle site" \
-    --adminpass="admin" \
-    --adminemail="admin@example.com"
+  php admin/cli/install_database.php \
+  --agree-license \
+  --fullname="Docker moodle" \
+  --shortname="docker_moodle" \
+  --summary="Docker moodle site" \
+  --adminpass="admin" \
+  --adminemail="admin@example.com"
 
 # configure HTTP security
 "$MOODLE_COMPOSE_CMD" exec webserver php admin/cli/cfg.php --name=curlsecurityblockedhosts --set=""
