fix certificate with behat tests

diff --git a/moodled b/moodled
--- a/moodled
+++ b/moodled
@@ -47,6 +47,24 @@ function checkExtraHost() {
 
 # moodle init
 function init() {
+  # generate self-signed certs for traefik
+  if [ ! -f "$PWD/certs/server.key" ]; then
+    mkdir -p "$PWD/certs"
+    openssl req -subj "/CN=$MOODLE_EXTRA_HOST" -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -keyout "$PWD"/certs/server.key -out "$PWD"/certs/server.crt
+    chmod -R 777 "$PWD/certs"
+  fi
+  # generate tls.yml for traefik
+  if [ ! -f "$PWD/certs/tls.yml" ]; then
+    cat >"$PWD/certs/tls.yml" <<EOF
+tls:
+  stores:
+    default:
+      defaultCertificate:
+        certFile: /certs/server.crt
+        keyFile: /certs/server.key
+EOF
+  fi
+
   if [ ! -d "$MOODLE_DOCKER_WWWROOT" ]; then
     git clone https://github.com/moodle/moodle.git --branch "$MOODLE_BRANCH" --single-branch --depth=1
     cd moodle/repository/ || exit
@@ -82,16 +100,18 @@ services:
       MOODLE_OCIS_CLIENT_SECRET: UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh
 
   selenium:
+    user: 0:0
     extra_hosts:
       - $MOODLE_EXTRA_HOST:host-gateway
 
   traefik:
-    image: traefik:v2.9.1
+    image: traefik:2.10.7
     command:
       - '--pilot.dashboard=false'
       - '--log.level=ERROR'
       - '--api.dashboard=true'
       - '--api.insecure=true'
+      - '--providers.file.directory=/certs'
       - '--providers.docker=true'
       - '--providers.docker.exposedbydefault=false'
       - '--entrypoints.web.address=:80'
@@ -110,6 +130,7 @@ services:
       - $MOODLE_EXTRA_HOST:host-gateway
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
+      - $PWD/certs:/certs
 EOF
   fi
 }
@@ -161,6 +182,27 @@ function startOcis() {
   done
 }
 
+# params
+# $1: cert file (full path)
+# $2: container name
+function copyCertFile() {
+  if [ "$1" == "" ]; then
+    echo -e "\e[31m[ERR] cert file path is required\e[0m"
+    exit 1
+  fi
+  if [ "$2" == "" ]; then
+    echo -e "\e[31m[ERR] container name is required\e[0m"
+    exit 1
+  fi
+  if [ -f "$1" ]; then
+    "$MOODLE_COMPOSE_CMD" cp "$1" "$2":/usr/local/share/ca-certificates/
+    "$MOODLE_COMPOSE_CMD" exec "$2" update-ca-certificates
+  else
+    echo -e "\e[31m[ERR] cert file not found:\e[0m $1"
+    exit 1
+  fi
+}
+
 function installMoodle() {
   if [ "$OCIS_CERTS_FILE" == "" ]; then
     echo -e "\e[31m[ERR] ocis cert file is required\e[0m"
@@ -168,13 +210,8 @@ function installMoodle() {
     exit 1
   fi
 
-  if [ -f "$OCIS_CERTS_FILE" ]; then
-    "$MOODLE_COMPOSE_CMD" cp "$OCIS_CERTS_FILE" webserver:/usr/local/share/ca-certificates/
-    "$MOODLE_COMPOSE_CMD" exec webserver update-ca-certificates
-  else
-    echo -e "\e[31m[ERR] ocis cert file not found:\e[0m $OCIS_CERTS_FILE"
-    exit 1
-  fi
+  copyCertFile "$OCIS_CERTS_FILE" webserver
+  copyCertFile "$PWD/certs/server.crt" selenium
 
   echo "Installing moodle..."
   "$MOODLE_DB_WAIT_CMD"
@@ -207,6 +244,11 @@ function help() {
   echo -e "  \e[36mpull\e[0m            pull docker images"
   echo -e "  \e[36mdown\e[0m            shutdown services"
 }
+
+# show help if no command
+if [ "$1" == "" ]; then
+  help
+fi
 
 # command options
 while [ $# -gt 0 ]; do
@@ -281,8 +323,5 @@ if [ "$CMD" == "up" ]; then
   startOcis
   # install moodle
   installMoodle
-fi
-
-if [ "$1" == "" ]; then
-  help
+  exit 0
 fi
